# Generated by Django 4.2.10 on 2025-04-08 19:52

import api.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_missing_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyaccesslog',
            name='details',
            field=api.utils.fields.EncryptedJSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='emergencyaccesslog',
            name='ip_address',
            field=api.utils.fields.EncryptedCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='emergencyaccesslog',
            name='user_agent',
            field=api.utils.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emergencypin',
            name='pin',
            field=api.utils.fields.EncryptedCharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='emergencypin',
            name='revoked_reason',
            field=api.utils.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='critical_health_info',
            field=api.utils.fields.EncryptedJSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='user',
            name='emergency_contacts',
            field=api.utils.fields.EncryptedJSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='hospital_name',
            field=api.utils.fields.EncryptedCharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='license_number',
            field=api.utils.fields.EncryptedCharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=api.utils.fields.EncryptedCharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=api.utils.fields.EncryptedCharField(blank=True, max_length=150),
        ),
    ]
