# Generated by Django 4.2.10 on 2025-04-08 20:06

from django.db import migrations, models
import django.db.models.deletion
import api.utils.fields
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_missing_fields'),
    ]

    operations = [
        # First, remove the problematic table
        migrations.RemoveField(
            model_name='emergencyaccesslog',
            name='user',
        ),
        migrations.DeleteModel(
            name='EmergencyAccessLog',
        ),
        
        # Then recreate it with proper encrypted fields
        migrations.CreateModel(
            name='EmergencyAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('GENERATED', 'PIN Generated'), ('VERIFIED', 'PIN Verified'), ('EXPIRED', 'PIN Expired'), ('REVOKED', 'Access Revoked'), ('FAILED', 'Failed Attempt')], max_length=20)),
                ('ip_address', api.utils.fields.EncryptedCharField(blank=True, max_length=100, null=True)),
                ('user_agent', api.utils.fields.EncryptedTextField(blank=True, null=True)),
                ('details', api.utils.fields.EncryptedJSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        # Add encrypted fields to User model
        migrations.AlterField(
            model_name='user',
            name='critical_health_info',
            field=api.utils.fields.EncryptedJSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='user',
            name='emergency_contacts',
            field=api.utils.fields.EncryptedJSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='hospital_name',
            field=api.utils.fields.EncryptedCharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='license_number',
            field=api.utils.fields.EncryptedCharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=api.utils.fields.EncryptedCharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=api.utils.fields.EncryptedCharField(blank=True, max_length=150),
        ),
        # Add encrypted fields to EmergencyPIN model
        migrations.AlterField(
            model_name='emergencypin',
            name='pin',
            field=api.utils.fields.EncryptedCharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='emergencypin',
            name='revoked_reason',
            field=api.utils.fields.EncryptedTextField(blank=True, null=True),
        ),
    ]
