# Generated by Django 4.2.10 on 2025-04-08 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_emergencyaccesslog_details_and_more'),
        ('api', '0005_fix_encrypted_fields'),
    ]

    operations = [
    ]
