# Generated by Django 4.2.10 on 2025-04-08 20:26

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


def fix_auth_errors(apps, schema_editor):
    """Fix any authentication errors by ensuring the database schema is consistent."""
    # First make sure the auth-related tables exist
    schema_editor.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_name = 'api_user'
            ) THEN
                CREATE TABLE IF NOT EXISTS api_user (
                    id SERIAL PRIMARY KEY,
                    password VARCHAR(128) NOT NULL,
                    last_login TIMESTAMP WITH TIME ZONE,
                    is_superuser BOOLEAN NOT NULL,
                    username VARCHAR(150) NOT NULL UNIQUE,
                    first_name VARCHAR(150) NOT NULL,
                    last_name VARCHAR(150) NOT NULL,
                    email VARCHAR(254) NOT NULL,
                    is_staff BOOLEAN NOT NULL,
                    is_active BOOLEAN NOT NULL,
                    date_joined TIMESTAMP WITH TIME ZONE NOT NULL,
                    role VARCHAR(10) NOT NULL
                );
            END IF;
        END
        $$;
        """
    )
    
    # Make sure token table exists (for JWT refresh tokens)
    schema_editor.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_name = 'token_blacklist_outstandingtoken'
            ) THEN
                CREATE TABLE IF NOT EXISTS token_blacklist_outstandingtoken (
                    id SERIAL PRIMARY KEY,
                    token TEXT NOT NULL,
                    created_at TIMESTAMP WITH TIME ZONE,
                    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
                    jti VARCHAR(255) NOT NULL UNIQUE,
                    user_id INTEGER REFERENCES api_user(id) ON DELETE CASCADE
                );
            END IF;
        END
        $$;
        """
    )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_merge_20250409_0144'),
    ]

    operations = [
        migrations.RunPython(fix_auth_errors),
    ]
